get_route_to() now returns all vrfs
napalm-automation/napalm-eos pull request #145
Opened 2017-02-28 18:34 UTC by kbirkeland

Added test case for multi-vrf environment

<!-- Make sure you have read http://napalm.readthedocs.io/en/latest/contributing/index.html --!>

2017-03-01 06:22 UTC, mirceaulinic requested changes
Hi @kbirkeland - thanks for this PR.

2017-03-01 06:22 UTC, mirceaulinic commented on napalm_eos/eos.py
> +            command = 'show ip{ipv} route vrf {_vrf} {destination} {protocol} detail'.format(
Please add this command in a list of commands, then execute all of them in a single request.
Then iterate through the complete reply.

2017-03-01 06:23 UTC, dbarrosop commented on napalm_eos/eos.py
> +
You are hardcoding the variable `vrf` so the `if..else` statement seems a bit unnecessary :)

2017-03-01 06:33 UTC, mirceaulinic commented on napalm_eos/eos.py
> +            vrfs = self.get_network_instances().keys()
Can we find a different way to get the list of VRFs on the device? `get_network_instances` is already pretty heavy and we don't want this method to depend on it.

2017-03-01 13:33 UTC, kbirkeland commented on napalm_eos/eos.py
> +
It is, but it makes the implementation of a vrf argument a simple change.  I can remove that if you want.

2017-03-01 13:44 UTC, kbirkeland commented on napalm_eos/eos.py
> +            vrfs = self.get_network_instances().keys()
See ca2c4f3a912eb127bfd6c7ce0e3d6d79f16209b0

2017-03-01 13:44 UTC, kbirkeland commented on napalm_eos/eos.py
> +            command = 'show ip{ipv} route vrf {_vrf} {destination} {protocol} detail'.format(
See ae695b469b7028dd098ea1704911b15654d97c69

2017-03-01 20:38 UTC, mirceaulinic approved these changes
Also this one looks good to me. I'll put it on hold till next week when I need to test it before getting this in. Thanks!

2017-03-14 15:55 UTC, merged

2017-03-14 15:55 UTC, mirceaulinic commented
Thanks @kbirkeland