populate 'remote_port_description' in get_lldp_neighbors_detail()
napalm-automation/napalm-eos pull request #176
Opened 2017-08-24 06:27 UTC by bholmgren

populate 'remote_port_description' in get_lldp_neighbors_detail(). It was simply assigning it to an empty string.

<!-- Make sure you have read http://napalm.readthedocs.io/en/latest/contributing/index.html --!>

2017-08-24 09:29 UTC, mirceaulinic requested changes
Thanks @bholmgren, this looks good.
Just please fix the tests and add the interface description in the expected data: https://github.com/napalm-automation/napalm-eos/blob/develop/test/unit/mocked_data/test_get_lldp_neighbors_detail/normal/expected_result.json

2017-08-25 00:17 UTC, bholmgren commented
I've updated the expected test results as required.

2017-08-28 09:05 UTC, dbarrosop commented
Nice one!

2017-08-28 09:05 UTC, dbarrosop approved these changes

2017-08-28 12:09 UTC, mirceaulinic approved these changes

2017-08-28 12:10 UTC, merged