Make use of mac() and ip() helpers.
napalm-automation/napalm-eos pull request #46
Opened 2016-09-17 13:47 UTC by inetuid

<!-- Make sure you have read http://napalm.readthedocs.io/en/latest/contributing/index.html --!>

2016-09-17 15:45 UTC, mirceaulinic approved these changes
This looks good @inetuid! Thanks!

2016-09-17 15:46 UTC, mirceaulinic commented on napalm_eos/eos.py
> +                        napalm_base.helpers.ip, item['remote_address']))
should be ```napalm_base.helpers.ip(item['remote_address']))```

2016-09-17 15:46 UTC, mirceaulinic commented on napalm_eos/eos.py
> +                        napalm_base.helpers.ip, item['router_id']))
should be ```napalm_base.helpers.ip(item['router_id']))```

2016-09-17 15:47 UTC, mirceaulinic commented on napalm_eos/eos.py
> +                        napalm_base.helpers.ip, item['local_address']))
should be ```napalm_base.helpers.ip(item['local_address']))```

2016-09-17 15:48 UTC, mirceaulinic requested changes
Just noticed that you missed some details, please update @inetuid

2016-09-17 15:52 UTC, mirceaulinic commented on napalm_eos/eos.py
> +                    'mac'       : napalm_base.helpers.mac(mac_format),
Here you can also use ```mac_raw``` instead of ```mac_format``` and remove the unnecessary lines.

2016-09-17 15:52 UTC, mirceaulinic commented on napalm_eos/eos.py
> +                    'mac'       : napalm_base.helpers.mac(mac_format),
Same here, can use ```mac_raw```

2016-09-17 15:53 UTC, mirceaulinic requested changes

2016-09-17 16:35 UTC, inetuid commented on napalm_eos/eos.py
> +                        napalm_base.helpers.ip, item['remote_address']))
convert() looks to call the first argument (napalm_base.helpers.ip) with the second argument (item['remote_address']):

```
def convert(to, who, default=u''):
    if who is None:
        return default
    try:
        return to(who)
    except:
        return default
```

So I don't think it's appropriate to pass napalm_base.helpers.ip(item['remote_address'])).

You could argue that the whole convert part is unnecessary, but I went for minimal changes.

2016-09-17 16:37 UTC, mirceaulinic commented on napalm_eos/eos.py
> +                        napalm_base.helpers.ip, item['remote_address']))
Right, missed that ```napalm_base.helpers.ip``` is passed as argument for ```convert```.

2016-09-17 16:38 UTC, mirceaulinic commented on napalm_eos/eos.py
> +                        napalm_base.helpers.ip, item['remote_address']))
And yeah. you can get rid of the convert - not needed anymore

2016-09-17 17:02 UTC, mirceaulinic approved these changes

2016-10-04 07:20 UTC, inetuid commented
Not sure if/what I need to do with this?

2016-10-05 01:27 UTC, mirceaulinic commented
@inetuid Can you please rebase?

2016-10-06 08:12 UTC, dbarrosop commented
If someone rebases this I will merge it and release a new version : )

2016-10-06 17:36 UTC, inetuid commented
Assuming a rebase is fixing the merge (not updating the commit log) I made a change but it's now failing the unit tests. The tests pass if I run them locally on my development box but fail under Travis. Looks like the case difference in the mac() method is causing the problem.

2016-10-06 17:58 UTC, mirceaulinic commented
@inetuid You did good rebasing. The new testing framework compares the expected data with the information returned by the getters - and seems to be case sensitive (e.g.: ```{"expected": "08:00:27:10:c4:8f", "result": "08:00:27:10:C4:8F"}```). For the moment you can update the contents of the tests to be update and all MAC addresses to be converted to upper in ```expected_result.json``` for the following tests:

- [get_arp_table](https://github.com/napalm-automation/napalm-eos/blob/develop/test/unit/mocked_data/test_get_arp_table/normal/expected_result.json) 
- [test_get_interfaces](https://github.com/napalm-automation/napalm-eos/blob/develop/test/unit/mocked_data/test_get_interfaces/normal/show_interfaces.json)

For traceroute, as the unresponsive hops are marked with *, you should do:

```python
hop_addr = hop_details[4+probe_index*5]
ip_address = napalm_base.helpers.convert(napalm_base.helpers.ip, hop_addr, hop_addr)
```

Which returns the raw value (*) in case unable to convert to ip format.

2016-10-06 21:36 UTC, mirceaulinic requested changes

2016-10-06 21:36 UTC, mirceaulinic commented on napalm_eos/eos.py
> +                ip_address = napalm_base.helpers.ip(hop_details[4+probe_index*5])
Replace with this @inetuid 

```python
hop_addr = hop_details[4+probe_index*5]
ip_address = napalm_base.helpers.convert(napalm_base.helpers.ip, hop_addr, hop_addr)
```

2016-10-21 12:09 UTC, inetuid commented
Changes made.

2016-10-24 09:49 UTC, merged